name: CustomItemRecipes
description: Create custom items and recipes, complete with API! Wow!
version: ${project.version}
website: http://robomwm.com
author: RoboMWM
main: com.robomwm.customitemrecipes.CustomItemRecipes
api-version: 1.13
commands:
  crecipe:
      usage: /crecipe <shaped/shapeless> <customitem name> - Note that recipes only use one item per slot.
      permission: customitemrecipes.crecipe
      aliases: [crecipes]
  citem:
      usage: /citem <list/name/register/get/lore>
      permission: customitemrecipes.citem
      aliases: [citems]
  cremove:
      usage: /cremove <name> - removes custom item and its recipes
      permission: customitemrecipes.cremove
permissions:
    customitemrecipes.*:
        description: Grants ALL THE THINGS
        children:
            customitemrecipes.citem: true
            customitemrecipes.crecipe: true
            customitemrecipes.cremove: true
    customitemrecipes.citem:
        description: Permission to /citem
        default: op
    customitemrecipes.crecipe:
        description: Permission to /crecipe
        default: op
    customitemrecipes.cremove:
        description: Permission to /cremove
        default: op
